FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Inject env variable at build time
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ARG MONGODB_URI
ENV MONGODB_URI=$MONGODB_URI
ARG MONGODB_DB
ENV MONGODB_DB=$MONGODB_DB

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
